name: commit

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

    - name: 'Run apt update'
      run: |
        apt update

    - name: 'Install packages'
      run: |
        apt install just gcc doxygen
    
    - name: 'Build the code'
      run: |
        just build

    - name: 'Test everything'
      run: |
        just test

